accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import CustomLoginView
from django.views.generic import TemplateView

app_name = 'accounts'

urlpatterns = [
    path('signup/',
        views.SignUpView.as_view(),
        name='signup'),

    path('signup_success/',
        views.SignUpSuccessView.as_view(),
        name='signup_success'),

    path('login/',
        auth_views.LoginView.as_view(template_name='login.html'),
        name='login'),

    path('logout/',
        auth_views.LogoutView.as_view(template_name='logout.html'),
        name='logout'),

    path('login/', CustomLoginView.as_view(), name='login'),

    path('login_success/', TemplateView.as_view(template_name='login_success.html'), name='login_success'),
]

uranaiapp/urls.py
from django.urls import path
from . import views
from .views import random_oracle

app_name = 'uranaiapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
# 大アルカナのカードの説明
    path('chariot_e/', views.Chariot_e.as_view(), name='chariot_e'),
    path('death_e/', views.Death_e.as_view(), name='death_e'),
    path('devil_e/', views.Devil_e.as_view(), name='devil_e'),
    path('devination/', views.Devination_e.as_view(), name='devination_e'),
    path('emperor/', views.Emperor_e.as_view(), name='emperor_e'),
    path('empress_e/', views.Empress_e.as_view(), name='empress_e'),
    path('fool_e/', views.Fool_e.as_view(), name='fool_e'),
    path('fortune_e/', views.Fortune_e.as_view(), name='fortune_e'),
    path('hermit_e/', views.Hermit_e.as_view(), name='hermit_e'),
    path('hierophant_e/', views.Hierophant_e.as_view(), name='hierophant_e'),
    path('judgement_e/', views.Judgement_e.as_view(), name='judgement_e'),
    path('justice_e/', views.Justice_e.as_view(), name='justice_e'),
    path('lover_e/', views.Lover_e.as_view(), name='lovers_e'),
    path('magician/', views.Magician_e.as_view(), name='magician_e'),
    path('man_e/', views.Man_e.as_view(), name='man_e'),
    path('moon/', views.Moon_e.as_view(), name='moon_e'),
    path('priestess_e/', views.Priestess_e.as_view(), name='priestess_e'),
    path('star_e/', views.Star_e.as_view(), name='star_e'),
    path('strength/', views.Strength_e.as_view(), name='strength_e'),
    path('sun_e/', views.Sun_e.as_view(), name='sun_e'),
    path('tower_e/', views.Tower_e.as_view(), name='tower_e'),
    path('temperance_e/', views.Temperance_e.as_view(), name='temperance_e'),
    path('world_e/', views.World_e.as_view(), name='world_e'),
# 小アルカナ
    path('wands/', views.Wands.as_view(), name='wands'),
    path('pentacles/', views.Pentacles.as_view(), name='pentacles'),
    path('cups/', views.Cups.as_view(), name='cups'),
    path('swords/', views.Swords.as_view(), name='swords'),
# 大アルカナの詳細説明
    path('E_one_oracle/', views.E_one_oracle.as_view(), name='E_one_oracle'),
    path('E_two_oracle/', views.E_twe_oracle.as_view(), name='E_two_oracle'),
    path('E_two_mind/', views.E_two_mind.as_view(), name='E_two_mind'),
    path('E_simple_cross/', views.E_simple_cross.as_view(), name='E_simple_cross'),
    path('E_three_card/', views.E_three_card.as_view(), name='E_three_card'),
    path('E_golden_trine/', views.E_golden_trine.as_view(), name='E_golden_trine'),
    path('E_four_card/', views.E_four_card.as_view(), name='E_four_card'),
    path('E_diamond_cross/', views.E_diamond_cross.as_view(), name='E_diamond_cross'),
    path('E_jupiter_spread/', views.E_jupiter_spread.as_view(), name='E_jupiter_spread'),
    path('E_treasure_triangle/', views.E_treasure_triangle.as_view(), name='E_treasure_triangle'),
    path('E_cross_spread/', views.E_cross_spread.as_view(), name='E_cross_spread'),
    path('E_greek_cross/', views.E_greek_cross.as_view(), name='E_greek_cross'),
    path('E_pentagram/', views.E_pentagram.as_view(), name='E_pentagram'),
    path('E_pyramid/', views.E_pyramid.as_view(), name='E_pyramid'),
    path('E_two_companies/', views.E_two_companies.as_view(), name='E_two_companies'),
    path('E_hexagram/', views.E_hexagram.as_view(), name='E_hexagram'),
    path('E_horseshoe/', views.E_horseshoe.as_view(), name='E_horseshoe'),
    path('E_seven_tailings/', views.E_seven_tailings.as_view(), name='E_seven_tailings'),
    path('E_seven_days/', views.E_seven_days.as_view(), name='E_seven_days'),
    path('E_spiritual_spread/', views.E_spiritual_spread.as_view(), name='E_spiritual_spread'),
    path('E_compatibility_method/', views.E_compatibility_method.as_view(), name='E_compatibility_method'),
    path('E_nine_card/', views.E_nine_card.as_view(), name='E_nine_card'),
    path('E_celtic_cross/', views.E_celtic_cross.as_view(), name='E_celtic_cross'),
    path('E_horoscope_spread/', views.E_horoscope_spread.as_view(), name='E_horoscope_spread'),
# ワンオラクルのランダムURL用
    path("random_result/", random_oracle, name="one_oracle_randam"),
]

uranaiproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uranaiapp.urls')),
    path('',include('accounts.urls')),
]

uranaiapp/models.py
from django.db import models

class Result(models.Model):  # models.Model を継承

    # タイトル用フィールド
    title = models.CharField(
        verbose_name='タイトル',
        max_length=30
    )

    # 本文用フィールド
    content = models.TextField(
        verbose_name='本文',
        max_length=300
    )

    # 写真用フィールド
    # image1 = models.ImageField(
    #     verbose_name='イメージ１',
    #     upload_to='photos'
    # )

    def __str__(self):
        return self.title

uranaiapp/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
import random
from django.shortcuts import redirect

# モデルResultをインポート
from .models import Result

class IndexView(TemplateView):
    template_name = 'index.html'

# 大アルカナカードの説明用
class Chariot_e(TemplateView):
    template_name = 'chariot_e.html'

class Death_e(TemplateView):
    template_name = 'death_e.html'

class Devil_e(TemplateView):
    template_name = 'devil_e.html'

class Devination_e(TemplateView):
    template_name = 'devination_e.html'

class Emperor_e(TemplateView):
    template_name = 'emperor_e.html'

class Empress_e(TemplateView):
    template_name = 'empress_e.html'

class Fool_e(TemplateView):
    template_name = 'fool_e.html'

class Strength_e(TemplateView):
    template_name = 'strength_e.html'

class Fortune_e(TemplateView):
    template_name = 'fortune_e.html'

class Hermit_e(TemplateView):
    template_name = 'hermit_e.html'

class Hierophant_e(TemplateView):
    template_name = 'hierophant_e.html'

class Judgement_e(TemplateView):
    template_name = 'judgement_e.html'

class Justice_e(TemplateView):
    template_name = 'justice_e.html'

class Lover_e(TemplateView):
    template_name= 'lovers_e.html'

class Magician_e(TemplateView):
    template_name = 'magician_e.html'

class Man_e(TemplateView):
    template_name = 'man_e.html'

class Moon_e(TemplateView):
    template_name = 'moon_e.html'

class Priestess_e(TemplateView):
    template_name = 'priestess_e.html'

class Star_e(TemplateView):
    template_name = 'star_e.html'

class Sun_e(TemplateView):
    template_name = 'sun_e.html'

class Tower_e(TemplateView):
    template_name = 'tower_e.html'

class Temperance_e(TemplateView):
    template_name = 'temperance_e.html'

class World_e(TemplateView):
    template_name = 'world_e.html'


# 小アルカナ
class Wands(TemplateView):
    template_name = 'wands.html'

class Pentacles(TemplateView):
    template_name = 'pentacles.html'

class Cups(TemplateView):
    template_name = 'cups.html'

class Swords(TemplateView):
    template_name = 'swords.html'

# 大アルカナの詳細の説明
class E_one_oracle(TemplateView):
    template_name = 'E_one_oracle.html'

class E_twe_oracle(TemplateView):
    template_name = 'E_two_oracle.html'

class E_two_mind(TemplateView):
    template_name = 'E_two_mind.html'

class E_simple_cross(TemplateView):
    template_name = 'E_simple_cross.html'

class E_three_card(TemplateView):
    template_name = 'E_three_card.html'

class E_golden_trine(TemplateView):
    template_name = 'E_golden_trine.html'

class E_four_card(TemplateView):
    template_name = 'E_four_card.html'

class E_diamond_cross(TemplateView):
    template_name = 'E_diamond_cross.html'

class E_jupiter_spread(TemplateView):
    template_name = 'E_jupiter_spread.html'

class E_treasure_triangle(TemplateView):
    template_name = 'E_treasure_triangle.html'

class E_cross_spread(TemplateView):
    template_name = 'E_cross_spread.html'

class E_greek_cross(TemplateView):
    template_name = 'E_greek_cross.html'

class E_pentagram(TemplateView):
    template_name = 'E_pentagram.html'

class E_pyramid(TemplateView):
    template_name = 'E_pyramid.html'

class E_two_companies(TemplateView):
    template_name = 'E_two_companies.html'

class E_hexagram(TemplateView):
    template_name = 'E_hexagram.html'

class E_horseshoe(TemplateView):
    template_name = 'E_horseshoe.html'

class E_seven_tailings(TemplateView):
    template_name = 'E_seven_tailings.html'

class E_seven_days(TemplateView):
    template_name = 'E_seven_days.html'

class E_spiritual_spread(TemplateView):
    template_name = 'E_spiritual_spread.html'

class E_compatibility_method(TemplateView):
    template_name = 'E_compatibility_method.html'

class E_nine_card(TemplateView):
    template_name = 'E_nine_card.html'

class E_celtic_cross(TemplateView):
    template_name = 'E_celtic_cross.html'

class E_horoscope_spread(TemplateView):
    template_name = 'E_horoscope_spread.html'

# ワンオラクルのランダムURL
def random_oracle(request):
    count = Result.objects.count()  # データの総数を取得
    if count == 0:
        result = None  # データがない場合はNoneを返す
    else:
        random_index = random.randint(0, count - 1)  # 0 から (count-1) の範囲でランダムな数値を取得
        result = Result.objects.all()[random_index]  # ランダムな1件を取得
    return render(request, "one_oracle_randam.html", {"result": result})

uranaiapp/templates/E_diamond_cross.html
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{% include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🎴 ダイヤモンドクロス 🎴</h1>
                        <h4 class="mt-4">7枚のカードで、複雑な問題を深く掘り下げる!
                        <br>ダイヤモンド型に配置して、キラリと答えを導く!</h4>
                    </div>
                </main>

                <!-- 「占う」ボタン -->
                <div class="position-absolute" style="bottom: 80px; left: 60%; transform: translateX(-50%);">
                    <a href="#" class="btn btn-primary btn-lg">🔮 占う 🔮</a>
                </div>

{% include "footer.html" %}

uranaiapp/templates/E_pentagram.html
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{% include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🎴 ペンタグラム 🎴</h1>
                        <h4 class="mt-4">5枚のカードを星型に配置し、
                        <br>人生の重要なポイントをキラリと輝かせるスプレッド!</h4>
                    </div>
                </main>

                <!-- 「占う」ボタン -->
                <div class="position-absolute" style="bottom: 80px; left: 60%; transform: translateX(-50%);">
                    <a href="#" class="btn btn-primary btn-lg">🔮 占う 🔮</a>
                </div>

{% include "footer.html" %}

uranaiapp/templates/E_simple_cross.html
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{% include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🎴 シンプルクロス 🎴</h1>
                        <h4 class="mt-4">4枚で十字型に配置!
                        <br>過去・現在・アドバイス・結果を見て、しっかり占っちゃおう!</h4>
                    </div>
                </main>

                <!-- 「占う」ボタン -->
                <div class="position-absolute" style="bottom: 80px; left: 60%; transform: translateX(-50%);">
                    <a href="#" class="btn btn-primary btn-lg">🔮 占う 🔮</a>
                </div>

{% include "footer.html" %}

uranaiapp/templates/E_two_oracle.html
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{% include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🎴 ツーオラクル 🎴</h1>
                        <h4 class="mt-4">2枚引いて、現在の状況と未来のアドバイスをゲット！
                        <br>1枚だけでは物足りないあなたにオススメ!</h4>
                    </div>
                </main>

                <!-- 「占う」ボタン -->
                <div class="position-absolute" style="bottom: 80px; left: 60%; transform: translateX(-50%);">
                    <a href="#" class="btn btn-primary btn-lg">🔮 占う 🔮</a>
                </div>

{% include "footer.html" %}

uranaiapp/templates/cups.html
<!-- 小アルカナのカップのカードの説明 -->
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{%include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🎴 CUPS 🎴</h1>
                        <h4 class="mt-4">カップの1 ：新しい愛、感情の高まり
                        <br>カップの2 ：パートナーシップ、調和、愛の絆
                        <br>カップの3 ：友情、祝福、楽しい時間
                        <br>カップの4 ：倦怠感、退屈、不満足
                        <br>カップの5 ：喪失、後悔、悲しみ
                        <br>カップの6 ：思い出、過去のつながり、純粋な愛
                        <br>カップの7 ：幻想、選択肢、迷い
                        <br>カップの8 ：新たな道、旅立ち、探求
                        <br>カップの9 ：願望成就、満足、幸福
                        <br>カップの10：家族の幸せ、調和、充実感
                        <br>カップのペイジ：ロマンチック、感受性豊か、創造性
                        <br>カップのナイト：愛情表現、夢想家、ロマンス
                        <br>カップのクイーン：共感、母性、感情の深さ
                        <br>カップのキング：感情の安定、理解力、寛容
                        </h4>

                    </div>
                </main>

{% include "footer.html" %}

uranaiapp/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>

uranaiapp/templates/man_e.html
<!-- 大アルカナの吊るされた男のカードの説明 -->
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{%include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🎴 MAN (吊るされた男) 🎴</h1>
                        <h4 class="mt-4">意味：試練・忍耐・犠牲・新しい視点
                        <br>逆位置：無駄な犠牲・頑固・停滞</h4>

                    </div>
                </main>

{% include "footer.html" %}

uranaiapp/templates/navbar.html
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="{% url 'uranaiapp:index' %}">うらなび！</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <!-- <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Nothing..." aria-label="Nothing..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form> -->
        <!-- Navbar-->
        <!-- <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown"> -->
                    <!-- ログインの有無で表示を変更する -->
                    <!-- <li>
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </li>
        </ul> -->
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="{% url 'uranaiapp:index' %}">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Home
                        </a>
                        <div class="sb-sidenav-menu-heading">Main</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            タロット占い
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">

uranaiapp/templates/one_oracle_emperor_t.html
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{% include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🏛 皇帝（The Emperor） 🏛</h1>
                        <h4 class="mt-4">正位置 ～ しっかりと地に足をつけ、人生を築こう!
                        <br>今のあなたに必要なのは、しっかりとした基盤を作ること!
                        <br>情熱や夢だけではなく、現実的な計画を立て、それを着実に実行していきましょう!
                        <br>リーダーシップを発揮し、責任を持って物事を進めることで、確かな成功が手に入ります!
                        <br>焦らず、一歩ずつ着実に積み上げることが大切!
                        <br>ルールを守りながらも、自分の理想とする未来を力強く築いていってください!</h4>
                    </div>
                </main>

                <!-- 「占う」ボタン -->
                <div class="position-absolute" style="bottom: 80px; left: 60%; transform: translateX(-50%);">
                    <a href="#" class="btn btn-primary btn-lg">🔮 占う 🔮</a>
                </div>

{% include "footer.html" %}

uranaiapp/templates/one_oracle_empress_t.html
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{% include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🌿 女帝（The Empress） 🌿</h1>
                        <h4 class="mt-4">正位置 ～ 豊かさと愛を受け入れ、自分を慈しもう
                        <br>あなたの周りには、愛と豊かさが溢れています!
                        <br>それをしっかり受け取り、人生を楽しんでください!
                        <br>今は努力よりも、心地よさや喜びを大切にする時期!
                        <br>無理に何かを変えようとせず、リラックスして自然の流れに身を任せてみましょう!
                        <br>特に人間関係や創造的な活動が豊かになる兆し!
                        <br>自分自身を大切にし、人にも優しさを与えることで、さらなる幸運が舞い込むでしょう!</h4>
                    </div>
                </main>

                <!-- 「占う」ボタン -->
                <div class="position-absolute" style="bottom: 80px; left: 60%; transform: translateX(-50%);">
                    <a href="#" class="btn btn-primary btn-lg">🔮 占う 🔮</a>
                </div>

{% include "footer.html" %}

uranaiapp/templates/one_oracle_magician_t.html
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{% include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🔮 魔術師（The Magician） 🔮</h1>
                        <h4 class="mt-4">正位置 ～ 自分の力を信じて、今こそ動き出すとき!
                        <br>あなたにはすでに、夢を叶えるための才能や道具が揃っています!
                        <br>必要なのは、それをどう活かすかを考えること!
                        <br>魔術師は「行動する人」
                        <br>思っているだけでは現実は変わりません!
                        <br>勇気を出して第一歩を踏み出し、持てる力を最大限に使ってみてください!
                        <br>自己表現を恐れず、自分を信じて進むことで、望む未来がグッと引き寄せられます
                        <br>今こそ、あなたのマジックを発揮するときです!</h4>
                    </div>
                </main>

                <!-- 「占う」ボタン -->
                <div class="position-absolute" style="bottom: 80px; left: 60%; transform: translateX(-50%);">
                    <a href="#" class="btn btn-primary btn-lg">🔮 占う 🔮</a>
                </div>

{% include "footer.html" %}

uranaiapp/templates/pentacles.html
<!-- 小アルカナのペンタクルのカードの説明 -->
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{%include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🎴 PENTACLES 🎴</h1>
                        <h4 class="mt-4">ペンタクルの1 ：新たな財産、チャンス、安定
                        <br>ペンタクルの2 ：バランス、柔軟性、適応力
                        <br>ペンタクルの3 ：チームワーク、技術の向上、協力
                        <br>ペンタクルの4 ：執着、貯蓄、保守的な態度
                        <br>ペンタクルの5 ：貧困、困難、孤立
                        <br>ペンタクルの6 ：施し、バランスの取れた経済状況
                        <br>ペンタクルの7 ：努力の成果、成長、長期的展望
                        <br>ペンタクルの8 ：努力、熟練、技術向上
                        <br>ペンタクルの9 ：成功、豊かさ、独立
                        <br>ペンタクルの10：家族の繁栄、伝統、安定
                        <br>ペンタクルのペイジ：学び、勤勉、新たなチャンス
                        <br>ペンタクルのナイト：堅実、誠実、忍耐強い
                        <br>ペンタクルのクイーン：現実的、豊かさ、思いやり
                        <br>ペンタクルのキング：経済的成功、安定、支配力
                        </h4>

                    </div>
                </main>

{% include "footer.html" %}

uranaiapp/templates/star_e.html
<!-- 大アルカナの星のカードの説明 -->
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{%include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🎴 STAR (星) 🎴</h1>
                        <h4 class="mt-4">意味：希望・癒し・インスピレーション・導き<br>逆位置：失望・悲観・方向性を見失う</h4>

                    </div>
                </main>

{% include "footer.html" %}

uranaiapp/templates/swords.html
<!-- 小アルカナのソードのカードの説明 -->
{% load static %}

{% include "header.html" %}

{% include "navbar.html" %}

{% include "devination.html"%}

{% include "card_explanation.html" %}

{%include "act.html" %}
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">🎴 SWORDS 🎴</h1>
                        <h4 class="mt-4">ソードの1 ：知性、決断、真実の発見
                        <br>ソードの2 ：迷い、葛藤、決断を先延ばし
                        <br>ソードの3 ：失恋、痛み、裏切り
                        <br>ソードの4 ：休息、回復、内省
                        <br>ソードの5 ：対立、不誠実、勝ち負け
                        <br>ソードの6 ：移動、解決策、新たな方向性
                        <br>ソードの7 ：策略、裏切り、計略
                        <br>ソードの8 ：束縛、不安、身動きが取れない
                        <br>ソードの9 ：悪夢、不安、ストレス
                        <br>ソードの10：終焉、痛みのピーク、裏切り
                        <br>ソードのペイジ：好奇心、警戒心、情報収集
                        <br>ソードのナイト：行動的、断固たる決意、急な変化
                        <br>ソードのクイーン：知的、冷静、公正
                        <br>ソードのキング：論理的、指導力、決断力
                            </h4>

                    </div>
                </main>

{% include "footer.html" %}